SELECT P.PRODUCT_CODE, SUM(P.PRICE * S.SALES_AMOUNT) AS TOTAL_SALES
FROM PRODUCT P
JOIN OFFLINE_SALE S ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY TOTAL_SALES DESC, P.PRODUCT_CODE ASC;