# SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
# FROM BOOK B
#     INNER JOIN AUTHOR A
#     ON B.AUTHOR_ID = A.AUTHOR_ID
# WHERE B.CATEGORY LIKE '경제'
# ORDER BY B.PUBLISHED_DATE ASC;


SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, DATE_FORMAT(BOOK.PUBLISHED_DATE, '%Y-%m-%d')AS PUBLISHED_DATE
FROM BOOK
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE BOOK.CATEGORY LIKE '경제'
ORDER BY BOOK.PUBLISHED_DATE ASC;